version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  # esdata:
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    # volumes:
      # - esdata:/usr/share/elasticsearch/data
    # environment:
      # - discovery.type=single-node
      # - discovery.zen.minimum_master_nodes=1
      # - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    # ports:
      # - "9200:9200"
      # - "9300:9300"
  cache:
    image: redis:alpine
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/code
    depends_on:
      - db
      # - esdata
      - cache
    ports:
      - "3000:3000"
    # links:
      # - esdata
# volumes:
  # web:
    # driver: local
  # esdata:
    # driver: local
